/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro1;

/**
 *
 * @author nipun
 */
public class Calculator extends javax.swing.JFrame {
    int iNum1,iNum2,iResult;
    char opperator;
    double dNum1,dNum2,dResult;
    boolean isIntFnum,isIntLnum;

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        displayTxtFld = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        oneBtn = new javax.swing.JButton();
        fourBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        zeroBtn = new javax.swing.JButton();
        eightBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JButton();
        fiveBtn = new javax.swing.JButton();
        floatBtn = new javax.swing.JButton();
        nineBtn = new javax.swing.JButton();
        sixBtn = new javax.swing.JButton();
        threeBtn = new javax.swing.JButton();
        plusBtn = new javax.swing.JButton();
        divideBtn = new javax.swing.JButton();
        subBtn = new javax.swing.JButton();
        multiBtn = new javax.swing.JButton();
        piBtn = new javax.swing.JButton();
        moduleBtn = new javax.swing.JButton();
        equalBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayTxtFld.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        displayTxtFld.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayTxtFld.setText("0");

        oneBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        oneBtn.setText("1");
        oneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtnActionPerformed(evt);
            }
        });

        fourBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fourBtn.setText("4");
        fourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBtnActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("7");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clearBtn.setText("C");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        zeroBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        zeroBtn.setText("0");
        zeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBtnActionPerformed(evt);
            }
        });

        eightBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eightBtn.setText("8");
        eightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBtnActionPerformed(evt);
            }
        });

        twoBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        twoBtn.setText("2");
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });

        fiveBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fiveBtn.setText("5");
        fiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBtnActionPerformed(evt);
            }
        });

        floatBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        floatBtn.setText(".");
        floatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floatBtnActionPerformed(evt);
            }
        });

        nineBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nineBtn.setText("9");
        nineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBtnActionPerformed(evt);
            }
        });

        sixBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sixBtn.setText("6");
        sixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBtnActionPerformed(evt);
            }
        });

        threeBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        threeBtn.setText("3");
        threeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBtnActionPerformed(evt);
            }
        });

        plusBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        plusBtn.setText("+");
        plusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusBtnActionPerformed(evt);
            }
        });

        divideBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        divideBtn.setText("/");
        divideBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideBtnActionPerformed(evt);
            }
        });

        subBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        subBtn.setText("-");
        subBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnActionPerformed(evt);
            }
        });

        multiBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        multiBtn.setText("*");
        multiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiBtnActionPerformed(evt);
            }
        });

        piBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        piBtn.setText("π");
        piBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piBtnActionPerformed(evt);
            }
        });

        moduleBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        moduleBtn.setText("%");
        moduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduleBtnActionPerformed(evt);
            }
        });

        equalBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        equalBtn.setText("=");
        equalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(displayTxtFld)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fourBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(oneBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(twoBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(eightBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(fiveBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(zeroBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(piBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moduleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(floatBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sixBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(threeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(multiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(subBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(divideBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(plusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)))
                            .addComponent(equalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(oneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(threeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(plusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(multiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(floatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(divideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(twoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(132, 132, 132)
                            .addComponent(zeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(piBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(moduleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(equalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtnActionPerformed
        if(displayTxtFld.getText().equals("0")){
            displayTxtFld.setText("1");
        }else{
            displayTxtFld.setText(displayTxtFld.getText()+"1");
        }
    }//GEN-LAST:event_oneBtnActionPerformed

    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
        if(displayTxtFld.getText().equals("0")){
            displayTxtFld.setText("2");
        }else{
            displayTxtFld.setText(displayTxtFld.getText()+"2");
        }
    }//GEN-LAST:event_twoBtnActionPerformed

    private void threeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBtnActionPerformed
        if(displayTxtFld.getText().equals("0")){
            displayTxtFld.setText("3");
        }else{
            displayTxtFld.setText(displayTxtFld.getText()+"3");
        }
    }//GEN-LAST:event_threeBtnActionPerformed

    private void fourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBtnActionPerformed
        if(displayTxtFld.getText().equals("0")){
            displayTxtFld.setText("4");
        }else{
            displayTxtFld.setText(displayTxtFld.getText()+"4");
        }
    }//GEN-LAST:event_fourBtnActionPerformed

    private void fiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBtnActionPerformed
        if(displayTxtFld.getText().equals("0")){
            displayTxtFld.setText("5");
        }else{
            displayTxtFld.setText(displayTxtFld.getText()+"5");
        }
    }//GEN-LAST:event_fiveBtnActionPerformed

    private void sixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBtnActionPerformed
        if(displayTxtFld.getText().equals("0")){
            displayTxtFld.setText("6");
        }else{
            displayTxtFld.setText(displayTxtFld.getText()+"6");
        }
    }//GEN-LAST:event_sixBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(displayTxtFld.getText().equals("0")){
            displayTxtFld.setText("7");
        }else{
            displayTxtFld.setText(displayTxtFld.getText()+"7");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void eightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBtnActionPerformed
        if(displayTxtFld.getText().equals("0")){
            displayTxtFld.setText("8");
        }else{
            displayTxtFld.setText(displayTxtFld.getText()+"8");
        }
    }//GEN-LAST:event_eightBtnActionPerformed

    private void nineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBtnActionPerformed
        if(displayTxtFld.getText().equals("0")){
            displayTxtFld.setText("9");
        }else{
            displayTxtFld.setText(displayTxtFld.getText()+"9");
        }
    }//GEN-LAST:event_nineBtnActionPerformed

    private void zeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBtnActionPerformed
        if(displayTxtFld.getText().equals("0")){
            displayTxtFld.setText("0");
        }else{
            displayTxtFld.setText(displayTxtFld.getText()+"0");
        }
    }//GEN-LAST:event_zeroBtnActionPerformed

    private void floatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floatBtnActionPerformed
        displayTxtFld.setText(displayTxtFld.getText()+".");
    }//GEN-LAST:event_floatBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        displayTxtFld.setText("0");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void plusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusBtnActionPerformed
        if(displayTxtFld.getText().contains(".")){
            dNum1=Double.parseDouble(displayTxtFld.getText());
            isIntFnum=false;
        }else{
            iNum1=Integer.parseInt(displayTxtFld.getText());
            isIntFnum=true;
        }
        opperator='+';
        displayTxtFld.setText("0");
    }//GEN-LAST:event_plusBtnActionPerformed

    private void subBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnActionPerformed
        if(displayTxtFld.getText().contains(".")){
            dNum1=Double.parseDouble(displayTxtFld.getText());
            isIntFnum=false;
        }else{
            iNum1=Integer.parseInt(displayTxtFld.getText());
            isIntFnum=true;
        }
        opperator='-';
        displayTxtFld.setText("0");
    }//GEN-LAST:event_subBtnActionPerformed

    private void multiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiBtnActionPerformed
        if(displayTxtFld.getText().contains(".")){
            dNum1=Double.parseDouble(displayTxtFld.getText());
            isIntFnum=false;
        }else{
            iNum1=Integer.parseInt(displayTxtFld.getText());
            isIntFnum=true;
        }
        opperator='*';
        displayTxtFld.setText("0");
    }//GEN-LAST:event_multiBtnActionPerformed

    private void divideBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideBtnActionPerformed
        if(displayTxtFld.getText().contains(".")){
            dNum1=Double.parseDouble(displayTxtFld.getText());
            isIntFnum=false;
        }else{
            iNum1=Integer.parseInt(displayTxtFld.getText());
            isIntFnum=true;
        }
        opperator='/';
        displayTxtFld.setText(displayTxtFld.getText()+"\n/\n");
    }//GEN-LAST:event_divideBtnActionPerformed

    private void piBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piBtnActionPerformed
        if(displayTxtFld.getText().equals("0")){
            displayTxtFld.setText("3.14");
            isIntFnum=false;
        }else{
            displayTxtFld.setText(displayTxtFld.getText()+"3.14");
            isIntFnum=true;
        }
    }//GEN-LAST:event_piBtnActionPerformed

    private void moduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleBtnActionPerformed
        if(displayTxtFld.getText().contains(".")){
            dNum1=Double.parseDouble(displayTxtFld.getText());
            isIntFnum=false;
        }else{
            iNum1=Integer.parseInt(displayTxtFld.getText());
            isIntFnum=true;
        }
        opperator='%';
        displayTxtFld.setText("0");
    }//GEN-LAST:event_moduleBtnActionPerformed

    private void equalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalBtnActionPerformed
        if(displayTxtFld.getText().contains(".")){
            dNum2=Double.parseDouble(displayTxtFld.getText());
            isIntLnum=false;
        }else{
            iNum2=Integer.parseInt(displayTxtFld.getText());
            isIntLnum=true;
        }
        if(isIntFnum && isIntLnum){
            if(opperator=='+'){
                displayTxtFld.setText(iNum1+"\n+\n"+iNum2+" = "+String.valueOf(iNum1+iNum2));
            }else if(opperator=='-'){
                displayTxtFld.setText(iNum1+"\n-\n"+iNum2+" = "+String.valueOf(iNum1-iNum2));
            }else if(opperator=='*'){
                displayTxtFld.setText(iNum1+"\n*\n"+iNum2+" = "+String.valueOf(iNum1*iNum2));
            }else if(opperator=='/'){
                displayTxtFld.setText(iNum1+"\n/\n"+iNum2+" = "+String.valueOf((double)iNum1/iNum2));
            }else if(opperator=='%'){
                displayTxtFld.setText(iNum1+"\n%\n"+iNum2+" = "+String.valueOf(iNum1%iNum2));
            }
        }else if(isIntFnum && (!isIntLnum)){
            if(opperator=='+'){
                displayTxtFld.setText(iNum1+"\n+\n"+dNum2+" = "+String.valueOf(iNum1+dNum2));
            }else if(opperator=='-'){
                displayTxtFld.setText(iNum1+"\n-\n"+dNum2+" = "+String.valueOf(iNum1-dNum2));
            }else if(opperator=='*'){
                displayTxtFld.setText(iNum1+"\n*\n"+dNum2+" = "+String.valueOf(iNum1*dNum2));
            }else if(opperator=='/'){
                displayTxtFld.setText(iNum1+"\n/\n"+dNum2+" = "+String.valueOf(iNum1/dNum2));
            }else if(opperator=='%'){
                displayTxtFld.setText(iNum1+"\n%\n"+dNum2+" = "+String.valueOf(iNum1%dNum2));
            }
        }else if((!isIntFnum) && isIntLnum){
            if(opperator=='+'){
                displayTxtFld.setText(dNum1+"\n+\n"+iNum2+" = "+String.valueOf(dNum1+iNum2));
            }else if(opperator=='-'){
                displayTxtFld.setText(dNum1+"\n-\n"+iNum2+" = "+String.valueOf(dNum1-iNum2));
            }else if(opperator=='*'){
                displayTxtFld.setText(dNum1+"\n*\n"+iNum2+" = "+String.valueOf(dNum1*iNum2));
            }else if(opperator=='/'){
                displayTxtFld.setText(dNum1+"\n/\n"+iNum2+" = "+String.valueOf(dNum1/iNum2));
            }else if(opperator=='%'){
                displayTxtFld.setText(dNum1+"\n%\n"+iNum2+" = "+String.valueOf(dNum1%iNum2));
            }
        }else if((!isIntFnum) && (!isIntLnum)){
            if(opperator=='+'){
                displayTxtFld.setText(dNum1+"\n+\n"+dNum2+" = "+String.valueOf(dNum1+dNum2));
            }else if(opperator=='-'){
                displayTxtFld.setText(dNum1+"\n-\n"+dNum2+" = "+String.valueOf(dNum1-dNum2));
            }else if(opperator=='*'){
                displayTxtFld.setText(dNum1+"\n*\n"+dNum2+" = "+String.valueOf(dNum1*dNum2));
            }else if(opperator=='/'){
                displayTxtFld.setText(dNum1+"\n/\n"+dNum2+" = "+String.valueOf(dNum1/dNum2));
            }else if(opperator=='%'){
                displayTxtFld.setText(dNum1+"\n%\n"+dNum2+" = "+String.valueOf(dNum1%dNum2));
            }
        }
    }//GEN-LAST:event_equalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField displayTxtFld;
    private javax.swing.JButton divideBtn;
    private javax.swing.JButton eightBtn;
    private javax.swing.JButton equalBtn;
    private javax.swing.JButton fiveBtn;
    private javax.swing.JButton floatBtn;
    private javax.swing.JButton fourBtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton moduleBtn;
    private javax.swing.JButton multiBtn;
    private javax.swing.JButton nineBtn;
    private javax.swing.JButton oneBtn;
    private javax.swing.JButton piBtn;
    private javax.swing.JButton plusBtn;
    private javax.swing.JButton sixBtn;
    private javax.swing.JButton subBtn;
    private javax.swing.JButton threeBtn;
    private javax.swing.JButton twoBtn;
    private javax.swing.JButton zeroBtn;
    // End of variables declaration//GEN-END:variables
}
